language: csharp
dotnet: 3.1.101
script: 
  - dotnet restore ./FSharp.Codecs.Redis.sln
  - dotnet build -c Release ./FSharp.Codecs.Redis.sln
  - dotnet run -p ./Tests/ -c Release -f netcoreapp3.1
  - dotnet run -p ./Tests/ -c Release -f netcoreapp2.1
